name: Build and Run Sedge

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:

      - name: Set start path
        id: set-start-path
        run: |
            echo "::set-output name=start_path::$(pwd)"

      - name: Download and build Sedge
        run: |
          echo "Downloading sedge sources..."
          cd ~
          git clone https://github.com/NethermindEth/sedge.git src --branch main --single-branch
          echo "Sources downloaded."
          cd src
          echo "Downloading missing dependency..."
          go mod download github.com/distribution/distribution/v3
          echo "Updating go-runewidth package..."
          go get github.com/mattn/go-runewidth@latest
          echo "Building sedge..."
          make compile

      - name: Run Sedge
        run: |
          cd /home/runner/src/build
          echo 'Running sedge...'
          ./sedge deps install >> $HOME/sedge.logs

          ./sedge generate --logging none -p $HOME full-node --map-all --no-mev-boost --no-validator --network chiado -c lighthouse:sigp/lighthouse:latest -e nethermind:nethermindeth/nethermind:master --el-extra-flag Sync.NonValidatorNode=true --el-extra-flag Sync.DownloadBodiesInFastSync=false --el-extra-flag Sync.DownloadReceiptsInFastSync=false --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/ >> $HOME/sedge.logs
          echo "Contents of the HOME/sedge.logs:"
          cat $HOME/sedge.logs
          mv $HOME/docker-compose.yml .
          mv $HOME/.env .
          echo "Contents of the current directory after move:"
          ls -la
          ./sedge run -p . >> $HOME/sedge.logs

      - name: Pause for 3 seconds
        run: sleep 3

      - name: Go back to start path
        run: |
          cd ${{ steps.set-start-path.outputs.start_path }}
          echo 'Start Dir'
          pwd

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: JSON-RPC verification
        run: mvn clean test

      - name: JSON-RPC Benchmark
        run: mvn gatling:test

      - name: Display sedge logs
        run: cat $HOME/sedge.logs
